# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kvHckyLpQdmr0RYJbI2OiVQSo7U74IWl
"""

def solution(s, n):
    l = list(s)
    for i in range(len(s)):
        if l[i].isupper():
            l[i] = chr((ord(l[i]) - ord('A') + n) % 26 + ord('A'))
        elif l[i].islower():
            l[i] = chr((ord(l[i]) - ord('a') + n) % 26 + ord('a'))
    return ''.join(l)