# -*- coding: utf-8 -*-
"""LV1_0000_프로그래머스_시저암호_구현_김영조.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RdL_z9nRHfd722AyFcuiTC93qcVuokaH
"""

def solution(s, n):
    l = ''
    for i in s:
        if (ord(i) >= 65 and ord(i) <= 90) or (ord(i) >= 97 and ord(i) <= 122):
            if (ord(i)+n) > 122 or ((ord(i)+n) > 90 and (ord(i)+n) < 97):
                l += chr(ord(i)+n-26)
            else:
                l += chr(ord(i)+n)
        else: 
            l += ' '
    return l