# -*- coding: utf-8 -*-
"""LV1_0000_프로그래머스_약수의합_구현_김영조.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RdL_z9nRHfd722AyFcuiTC93qcVuokaH
"""

def solution(n):
    l = 0
    for i in range(1, (int(n/2)+1)):
        if n % i == 0:
            l += i
    return l + n