# -*- coding: utf-8 -*-
"""LV1_0000_프로그래머스_문자열섞기_구현_김영조.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RdL_z9nRHfd722AyFcuiTC93qcVuokaH
"""

def solution(str1, str2):
    l = []
    for i in range(len(str1)):
        l.append(str1[i])
        l.append(str2[i])

    return ''.join(l)

solution('aaaaa', 'bbbbb')