# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_짝수와 홀수_민수.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKVhps7jMuC3e2mBojQJdR-vS0H8h-dy
"""

def solution(num):
    answer = ''
    if num%2==0:
        answer ="Even"
    else:
        answer ="Odd"
    return answer