# -*- coding: utf-8 -*-
"""Lv1_0000_프로그래머스_약수의합_구현_재혁.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1to2FWbMntapmPc0pLVdz2jyqrAKrcp8N
"""

def sol(n):
    return sum([i for i in range(1, n+1) if n % i == 0])