# -*- coding: utf-8 -*-
"""Lv1_프로그래머스_자릿수더하기_구현_재혁.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1to2FWbMntapmPc0pLVdz2jyqrAKrcp8N
"""

def solution(N):
    answer = [int(i) for i in str(N)]
    return sum(answer)