# -*- coding: utf-8 -*-
"""Lv1_0000_프로그래머스_짝수와홀수_구현_재혁.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1to2FWbMntapmPc0pLVdz2jyqrAKrcp8N
"""

def solution(num):
    if num % 2 == 0:
        return 'Even'
    else:
        return 'Odd'